//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySecurity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SecurityInfoWCFService")]
    public partial class User : object
    {
        
        private string BranchCodeField;
        
        private string DepartmentNameField;
        
        private string EmailAddressField;
        
        private bool EnabledField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private bool MustChangePasswordField;
        
        private string SQLPasswordField;
        
        private string TelephoneField;
        
        private int UserIDField;
        
        private string UserNameField;
        
        private int UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MustChangePassword
        {
            get
            {
                return this.MustChangePasswordField;
            }
            set
            {
                this.MustChangePasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SQLPassword
        {
            get
            {
                return this.SQLPasswordField;
            }
            set
            {
                this.SQLPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/SecurityInfoWCFService")]
    public partial class Role : object
    {
        
        private string DescriptionField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://schemas.datacontract.org/2004/07/SecurityInfoWCFService")]
    public partial class Attribute : object
    {
        
        private string DescriptionField;
        
        private string NameField;
        
        private string SourceTypeField;
        
        private string SourceValueField;
        
        private string TypeField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                this.SourceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceValue
        {
            get
            {
                return this.SourceValueField;
            }
            set
            {
                this.SourceValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Xml", Namespace="http://schemas.datacontract.org/2004/07/SecurityInfoWCFService")]
    public partial class Xml : object
    {
        
        private string AttributesField;
        
        private string ProfileField;
        
        private string RolesField;
        
        private string UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profile
        {
            get
            {
                return this.ProfileField;
            }
            set
            {
                this.ProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SurveySecurity.ISecurityInfoWCFService")]
    public interface ISecurityInfoWCFService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetUserInfo", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<SurveySecurity.User> GetUserInfoAsync(string UserName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetRoleInfo", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetRoleInfoResponse")]
        System.Threading.Tasks.Task<SurveySecurity.Role[]> GetRoleInfoAsync(string UserName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetAttributeInfo", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetAttributeInfoResponse")]
        System.Threading.Tasks.Task<SurveySecurity.Attribute[]> GetAttributeInfoAsync(string Application, string UserName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetXmlInfo", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetXmlInfoResponse")]
        System.Threading.Tasks.Task<SurveySecurity.Xml> GetXmlInfoAsync(string Application, string UserName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetXmlInfoByEmail", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetXmlInfoByEmailResponse")]
        System.Threading.Tasks.Task<SurveySecurity.Xml> GetXmlInfoByEmailAsync(string Application, string UserEmail, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/IsInRole", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/IsInRoleResponse")]
        System.Threading.Tasks.Task<bool> IsInRoleAsync(string UserName, string RoleName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetAttributeValue", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetAttributeValueResponse")]
        System.Threading.Tasks.Task<string> GetAttributeValueAsync(string Application, string UserName, string AttributeName, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/HasAttributeValue", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/HasAttributeValueResponse")]
        System.Threading.Tasks.Task<bool> HasAttributeValueAsync(string Application, string UserName, string AttributeName, string AttributeValue, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetUsersByBranchList", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetUsersByBranchListResponse")]
        System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersByBranchListAsync(string BranchList, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetUsersByUserList", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetUsersByUserListResponse")]
        System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersByUserListAsync(string UserList, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/GetUsersWithAttribute", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/GetUsersWithAttributeResponse")]
        System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersWithAttributeAsync(string ApplicationName, string AttributeName, string AttributeValue, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/UpdateEmailAddress", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/UpdateEmailAddressResponse")]
        System.Threading.Tasks.Task<int> UpdateEmailAddressAsync(string UserName, string EmailAddress, string Environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityInfoWCFService/UpdateTelephone", ReplyAction="http://tempuri.org/ISecurityInfoWCFService/UpdateTelephoneResponse")]
        System.Threading.Tasks.Task<int> UpdateTelephoneAsync(string UserName, string Telephone, string Environment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface ISecurityInfoWCFServiceChannel : SurveySecurity.ISecurityInfoWCFService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class SecurityInfoWCFServiceClient : System.ServiceModel.ClientBase<SurveySecurity.ISecurityInfoWCFService>, SurveySecurity.ISecurityInfoWCFService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecurityInfoWCFServiceClient() : 
                base(SecurityInfoWCFServiceClient.GetDefaultBinding(), SecurityInfoWCFServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISecurityInfoWCFService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityInfoWCFServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SecurityInfoWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), SecurityInfoWCFServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityInfoWCFServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecurityInfoWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityInfoWCFServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecurityInfoWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityInfoWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.User> GetUserInfoAsync(string UserName, string Environment)
        {
            return base.Channel.GetUserInfoAsync(UserName, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.Role[]> GetRoleInfoAsync(string UserName, string Environment)
        {
            return base.Channel.GetRoleInfoAsync(UserName, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.Attribute[]> GetAttributeInfoAsync(string Application, string UserName, string Environment)
        {
            return base.Channel.GetAttributeInfoAsync(Application, UserName, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.Xml> GetXmlInfoAsync(string Application, string UserName, string Environment)
        {
            return base.Channel.GetXmlInfoAsync(Application, UserName, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.Xml> GetXmlInfoByEmailAsync(string Application, string UserEmail, string Environment)
        {
            return base.Channel.GetXmlInfoByEmailAsync(Application, UserEmail, Environment);
        }
        
        public System.Threading.Tasks.Task<bool> IsInRoleAsync(string UserName, string RoleName, string Environment)
        {
            return base.Channel.IsInRoleAsync(UserName, RoleName, Environment);
        }
        
        public System.Threading.Tasks.Task<string> GetAttributeValueAsync(string Application, string UserName, string AttributeName, string Environment)
        {
            return base.Channel.GetAttributeValueAsync(Application, UserName, AttributeName, Environment);
        }
        
        public System.Threading.Tasks.Task<bool> HasAttributeValueAsync(string Application, string UserName, string AttributeName, string AttributeValue, string Environment)
        {
            return base.Channel.HasAttributeValueAsync(Application, UserName, AttributeName, AttributeValue, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersByBranchListAsync(string BranchList, string Environment)
        {
            return base.Channel.GetUsersByBranchListAsync(BranchList, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersByUserListAsync(string UserList, string Environment)
        {
            return base.Channel.GetUsersByUserListAsync(UserList, Environment);
        }
        
        public System.Threading.Tasks.Task<SurveySecurity.User[]> GetUsersWithAttributeAsync(string ApplicationName, string AttributeName, string AttributeValue, string Environment)
        {
            return base.Channel.GetUsersWithAttributeAsync(ApplicationName, AttributeName, AttributeValue, Environment);
        }
        
        public System.Threading.Tasks.Task<int> UpdateEmailAddressAsync(string UserName, string EmailAddress, string Environment)
        {
            return base.Channel.UpdateEmailAddressAsync(UserName, EmailAddress, Environment);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTelephoneAsync(string UserName, string Telephone, string Environment)
        {
            return base.Channel.UpdateTelephoneAsync(UserName, Telephone, Environment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISecurityInfoWCFService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISecurityInfoWCFService))
            {
                return new System.ServiceModel.EndpointAddress("http://wsd.nunyabusiness.com/SecurityInfoWCF/SecurityInfoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SecurityInfoWCFServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISecurityInfoWCFService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SecurityInfoWCFServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISecurityInfoWCFService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISecurityInfoWCFService,
        }
    }
}
